version: '3.9'

services:
  api:
    build:
      context: .
    env_file:
      - .env.prod
    environment:
      APP_ENV: production
      HTTP_LISTEN_PORT: 3000
    depends_on:
      - postgres
    networks:
      api-orders:
    ports:
      - "3030:3000"

networks:
  api-orders:
