all:
  vars:
    host_key_checking: false
  children:
    app:
      hosts:
        srv_selectel:
          ansible_connection: ssh
          ansible_user: root
          ansible_ssh_private_key_file: /root/ssh_keys/test_server_openssh_private_key
          ansible_host: 37.228.116.222
          ansible_port: 22
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
